version: '3.3'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_smartphones_db
      - POSTGRES_USER=jorge
      - POSTGRES_PASSWORD=jorge
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
    external: true